#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "omeka-classic"
name = "Omeka Classic"
description.en = "Web publishing platform for sharing digital collections and creating media-rich online exhibits"
description.fr = "Plate-forme de publication Web pour le partage de collections numériques et la création d'expositions en ligne riches en contenu multimédia"

version = "3.1.2~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "GPL-3.0"
website = "https://omeka.org/classic/"
demo = "https://demo.example.com"
admindoc = "https://yunohost.org/packaging_apps"
userdoc = "https://yunohost.org/apps"
code = "https://github.com/omeka/Omeka/"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/omeka"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["fr", "en"]
    default = "fr"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/omeka/Omeka/releases/download/v3.1.2/omeka-3.1.2.zip"
    sha256 = "b407c73948c703a9c5b92009aac88ea90c6bcfb7262dc8e8c440b2a145009607"

    # autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    #[resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "mariadb-server, php8.3-fpm, php8.3-mysql, php8.3-curl, php8.3-intl, php8.3-mbstring, php8.3-xmlrpc, php8.3-gd, php8.3-xml, php8.3-cli, php8.3-zip"

    [resources.database]
    type = "mysql"
